---
engines:
  eslint:
    enabled: true
exclude_patterns:
  - "**/__tests__"
  - "**/constants"
  - "**/locales"
  - "/src/routeTable.js"
  - "mock/"
  - "config/"
  - "scripts/"
  - "static/"
  - "webpack/"
