instrumentation:
  root: src
  include-all-sources: true
  excludes: [
    'server/index.js',
    'server/main.js',
    'server/config.js',
    'server/mainCss.js',
    'server/mainServer.js',
    'server/middleware/dev.js',
    'web/main.jsx',
    'web/store.js',
    'web/sagas/index.js',
    'web/forms/index.js',
  ]

  extensions:
    - .jsx
    - .js
