export const APP_MOUNTED = 'APP_MOUNTED';
export const LOCALE_CHANGED = 'LOCALE_CHANGED';
export const LOCALE_PREFERENCES_CHANGED = 'LOCALE_PREFERENCES_CHANGED';
export const REDIRECT = 'REDIRECT';
export const SESSION_SET_LANGUAGE = 'SESSION_SET_LANGUAGE';
