export const APP_MOUNTED = 'APP_MOUNTED';
export const GEOCODE_LOCATION_FETCH_ERROR = 'GEOCODE_LOCATION_FETCH_ERROR';
export const GEOCODE_LOCATION_FETCH_STARTED = 'GEOCODE_LOCATION_FETCH_STARTED';
export const GEOCODE_LOCATION_FETCH_SUCCESS = 'GEOCODE_LOCATION_FETCH_SUCCESS';
export const GEOCODE_LOCATIONS_RESET = 'GEOCODE_LOCATIONS_RESET';
export const LOCALE_CHANGED = 'LOCALE_CHANGED';
export const LOCALE_PREFERENCES_CHANGED = 'LOCALE_PREFERENCES_CHANGED';
export const SESSION_SET_LANGUAGE = 'SESSION_SET_LANGUAGE';
