export const ACCOMODATION_REQUIRED = 'ACCOMODATION_REQUIRED';
export const ACCOMODATION_FETCH_STARTED = 'ACCOMODATION_FETCH_STARTED';
export const ACCOMODATION_FETCH_SUCCESS = 'ACCOMODATION_FETCH_SUCCESS';
export const ACCOMODATION_FETCH_ERROR = 'ACCOMODATION_FETCH_ERROR';
