export const ACCOMODATION_MOUNTED = 'ACCOMODATION_MOUNTED';
export const APP_MOUNTED = 'APP_MOUNTED';
export const ARCHIVED_YEAR_MOUNTED = 'ARCHIVED_YEAR_MOUNTED';
export const CONDITIONS_MOUNTED = 'CONDITIONS_MOUNTED';
export const FEES_MOUNTED = 'FEES_MOUNTED';
export const FOOD_MOUNTED = 'FOOD_MOUNTED';
export const HOME_MOUNTED = 'HOME_MOUNTED';
export const NEWS_DETAIL_MOUNTED = 'NEWS_DETAIL_MOUNTED';
export const PERFORMER_DETAIL_MOUNTED = 'PERFORMER_DETAIL_MOUNTED';
export const REQUEST_PARTICIPANT_DETAILS = 'REQUEST_PARTICIPANT_DETAILS';
export const REQUEST_WORKSHOP_LOCATIONS = 'REQUEST_WORKSHOP_LOCATIONS';
export const SCHEDULE_MOUNTED = 'SCHEDULE_MOUNTED';
export const SIGNUP_MOUNTED = 'SIGNUP_MOUNTED';
export const TIPS_MOUNTED = 'TIPS_MOUNTED';
export const WORKSHOP_DETAIL_MOUNTED = 'WORKSHOP_DETAIL_MOUNTED';
export const WORKSHOPS_MOUNTED = 'WORKSHOPS_MOUNTED';

export const ACCOMODATION_FETCH_STARTED = 'ACCOMODATION_FETCH_STARTED';
export const ACCOMODATION_FETCH_SUCCESS = 'ACCOMODATION_FETCH_SUCCESS';
export const ACCOMODATION_FETCH_ERROR = 'ACCOMODATION_FETCH_ERROR';

export const ARCHIVED_YEAR_FETCH_STARTED = 'ARCHIVED_YEAR_FETCH_STARTED';
export const ARCHIVED_YEAR_FETCH_SUCCESS = 'ARCHIVED_YEAR_FETCH_SUCCESS';
export const ARCHIVED_YEAR_FETCH_ERROR = 'ARCHIVED_YEAR_FETCH_ERROR';

export const CONDITIONS_CURRENT_FETCH_STARTED = 'CONDITIONS_CURRENT_FETCH_STARTED';
export const CONDITIONS_CURRENT_FETCH_SUCCESS = 'CONDITIONS_CURRENT_FETCH_SUCCESS';
export const CONDITIONS_CURRENT_FETCH_ERROR = 'CONDITIONS_CURRENT_FETCH_ERROR';

export const FORM_FIELD_CHANGE = 'FORM_FIELD_CHANGE';
export const FORM_SUBMIT = 'FORM_SUBMIT';
export const FORM_SUBMIT_ALLOWED = 'FORM_SUBMIT_ALLOWED';
export const FORM_SUBMIT_PREVENTED = 'FORM_SUBMIT_PREVENTED';
export const FORM_SUBMIT_STARTED = 'FORM_SUBMIT_STARTED';
export const FORM_SUBMIT_SUCCESS = 'FORM_SUBMIT_SUCCESS';
export const FORM_SUBMIT_ERROR = 'FORM_SUBMIT_ERROR';
export const FORM_VALUES_VALIDATE = 'FORM_VALUES_VALIDATE';
export const FORM_VALUES_CLEAR = 'FORM_VALUES_CLEAR';
export const FORM_VALUES_SET = 'FORM_VALUES_SET';

export const GEOCODE_LOCATION_FETCH_STARTED = 'GEOCODE_LOCATION_FETCH_STARTED';
export const GEOCODE_LOCATION_FETCH_SUCCESS = 'GEOCODE_LOCATION_FETCH_SUCCESS';
export const GEOCODE_LOCATION_FETCH_ERROR = 'GEOCODE_LOCATION_FETCH_ERROR';

export const LECTOR_ROLES_FETCH_STARTED = 'LECTOR_ROLES_FETCH_STARTED';
export const LECTOR_ROLES_FETCH_SUCCESS = 'LECTOR_ROLES_FETCH_SUCCESS';
export const LECTOR_ROLES_FETCH_ERROR = 'LECTOR_ROLES_FETCH_ERROR';

export const LECTORS_FETCH_STARTED = 'LECTORS_FETCH_STARTED';
export const LECTORS_FETCH_SUCCESS = 'LECTORS_FETCH_SUCCESS';
export const LECTORS_FETCH_ERROR = 'LECTORS_FETCH_ERROR';

export const MEALS_FETCH_STARTED = 'MEALS_FETCH_STARTED';
export const MEALS_FETCH_SUCCESS = 'MEALS_FETCH_SUCCESS';
export const MEALS_FETCH_ERROR = 'MEALS_FETCH_ERROR';

export const NEWS_FETCH_STARTED = 'NEWS_FETCH_STARTED';
export const NEWS_FETCH_SUCCESS = 'NEWS_FETCH_SUCCESS';
export const NEWS_FETCH_ERROR = 'NEWS_FETCH_ERROR';

export const NEWS_DETAIL_FETCH_STARTED = 'NEWS_DETAIL_FETCH_STARTED';
export const NEWS_DETAIL_FETCH_SUCCESS = 'NEWS_DETAIL_FETCH_SUCCESS';
export const NEWS_DETAIL_FETCH_ERROR = 'NEWS_DETAIL_FETCH_ERROR';

export const SIGNUP_SUBMIT_STARTED = 'SIGNUP_SUBMIT_STARTED';
export const SIGNUP_SUBMIT_SUCCESS = 'SIGNUP_SUBMIT_SUCCESS';
export const SIGNUP_SUBMIT_ERROR = 'SIGNUP_SUBMIT_ERROR';

export const ORDER_CANCEL_FETCH_ERROR = 'ORDER_CANCEL_FETCH_ERROR';
export const ORDER_CANCEL_FETCH_STARTED = 'ORDER_CANCEL_FETCH_STARTED';
export const ORDER_CANCEL_FETCH_SUCCESS = 'ORDER_CANCEL_FETCH_SUCCESS';
export const ORDER_CANCEL_REQUESTED = 'ORDER_CANCEL_REQUESTED';
export const ORDER_CANCELED = 'ORDER_CANCELED';
export const ORDER_CONFIRM_FETCH_ERROR = 'ORDER_CONFIRM_FETCH_ERROR';
export const ORDER_CONFIRM_FETCH_STARTED = 'ORDER_CONFIRM_FETCH_STARTED';
export const ORDER_CONFIRM_FETCH_SUCCESS = 'ORDER_CONFIRM_FETCH_SUCCESS';
export const ORDER_CONFIRM_REQUESTED = 'ORDER_CONFIRM_REQUESTED';
export const ORDER_CONFIRMED = 'ORDER_CONFIRMED';
export const ORDER_CREATED = 'ORDER_CREATED';
export const ORDER_FETCH_ERROR = 'ORDER_FETCH_ERROR';
export const ORDER_FETCH_STARTED = 'ORDER_FETCH_STARTED';
export const ORDER_FETCH_SUCCESS = 'ORDER_FETCH_SUCCESS';
export const ORDER_FORM_MOUNTED = 'ORDER_FORM_MOUNTED';
export const ORDER_FORM_UNMOUNTED = 'ORDER_FORM_UNMOUNTED';

export const PARTICIPANT_REGISTERED = 'PARTICIPANT_REGISTERED';
export const PARTICIPANT_LOGIN = 'PARTICIPANT_LOGIN';
export const PARTICIPANT_LOGIN_AUTO = 'PARTICIPANT_LOGIN_AUTO';
export const PARTICIPANT_LOGOUT = 'PARTICIPANT_LOGOUT';
export const PARTICIPANT_FETCH_STARTED = 'PARTICIPANT_FETCH_STARTED';
export const PARTICIPANT_FETCH_SUCCESS = 'PARTICIPANT_FETCH_SUCCESS';
export const PARTICIPANT_FETCH_ERROR = 'PARTICIPANT_FETCH_ERROR';

export const PARTICIPANT_PASSWORD_CHANGE_STARTED = 'PARTICIPANT_PASSWORD_CHANGE_STARTED';
export const PARTICIPANT_PASSWORD_CHANGE_SUCCESS = 'PARTICIPANT_PASSWORD_CHANGE_SUCCESS';
export const PARTICIPANT_PASSWORD_CHANGE_ERROR = 'PARTICIPANT_PASSWORD_CHANGE_ERROR';

export const PARTICIPANT_PASSWORD_NEW_STARTED = 'PARTICIPANT_PASSWORD_NEW_STARTED';
export const PARTICIPANT_PASSWORD_NEW_SUCCESS = 'PARTICIPANT_PASSWORD_NEW_SUCCESS';
export const PARTICIPANT_PASSWORD_NEW_ERROR = 'PARTICIPANT_PASSWORD_NEW_ERROR';

export const PARTICIPANT_TOKEN_REVOKE_START = 'PARTICIPANT_TOKEN_REVOKE_START';
export const PARTICIPANT_TOKEN_REVOKE_SUCCESS = 'PARTICIPANT_TOKEN_REVOKE_SUCCESS';
export const PARTICIPANT_TOKEN_REVOKE_ERROR = 'PARTICIPANT_TOKEN_REVOKE_ERROR';

export const PARTICIPANT_ORDERS_FETCH_STARTED = 'PARTICIPANT_ORDERS_FETCH_STARTED';
export const PARTICIPANT_ORDERS_FETCH_SUCCESS = 'PARTICIPANT_ORDERS_FETCH_SUCCESS';
export const PARTICIPANT_ORDERS_FETCH_ERROR = 'PARTICIPANT_ORDERS_FETCH_ERROR';

export const PERFORMER_DETAIL_FETCH_ERROR = 'PERFORMER_DETAIL_FETCH_ERROR';
export const PERFORMER_DETAIL_FETCH_STARTED = 'PERFORMER_DETAIL_FETCH_STARTED';
export const PERFORMER_DETAIL_FETCH_SUCCESS = 'PERFORMER_DETAIL_FETCH_SUCCESS';
export const PERFORMERS_FETCH_ERROR = 'PERFORMERS_FETCH_ERROR';
export const PERFORMERS_FETCH_STARTED = 'PERFORMERS_FETCH_STARTED';
export const PERFORMERS_FETCH_SUCCESS = 'PERFORMERS_FETCH_SUCCESS';

export const POLL_VOTE = 'POLL_VOTE';

export const SCHEDULE_EVENTS_FETCH_STARTED = 'SCHEDULE_EVENTS_FETCH_STARTED';
export const SCHEDULE_EVENTS_FETCH_SUCCESS = 'SCHEDULE_EVENTS_FETCH_SUCCESS';
export const SCHEDULE_EVENTS_FETCH_ERROR = 'SCHEDULE_EVENTS_FETCH_ERROR';

export const SIGNUPS_OPEN = 'SIGNUPS_OPEN';

export const TEAMS_FETCH_STARTED = 'TEAMS_FETCH_STARTED';
export const TEAMS_FETCH_SUCCESS = 'TEAMS_FETCH_SUCCESS';
export const TEAMS_FETCH_ERROR = 'TEAMS_FETCH_ERROR';

export const TEXT_FETCH_STARTED = 'TEXT_FETCH_STARTED';
export const TEXT_FETCH_SUCCESS = 'TEXT_FETCH_SUCCESS';
export const TEXT_FETCH_ERROR = 'TEXT_FETCH_ERROR';

export const TIPS_FETCH_STARTED = 'TIPS_FETCH_STARTED';
export const TIPS_FETCH_SUCCESS = 'TIPS_FETCH_SUCCESS';
export const TIPS_FETCH_ERROR = 'TIPS_FETCH_ERROR';

export const MAGIC_DOOR_TOKEN = 'idui1raKzie8QuieKei6exeiOhsaeva4vooL4ao3ahx8EiquLoothei3Ha9shaki';

export const WORKSHOP_DETAIL_FETCH_STARTED = 'WORKSHOP_DETAIL_FETCH_STARTED';
export const WORKSHOP_DETAIL_FETCH_SUCCESS = 'WORKSHOP_DETAIL_FETCH_SUCCESS';
export const WORKSHOP_DETAIL_FETCH_ERROR = 'WORKSHOP_DETAIL_FETCH_ERROR';

export const WORKSHOP_DIFFICULTIES_FETCH_STARTED = 'WORKSHOP_DIFFICULTIES_FETCH_STARTED';
export const WORKSHOP_DIFFICULTIES_FETCH_SUCCESS = 'WORKSHOP_DIFFICULTIES_FETCH_SUCCESS';
export const WORKSHOP_DIFFICULTIES_FETCH_ERROR = 'WORKSHOP_DIFFICULTIES_FETCH_ERROR';

export const WORKSHOP_LOCATIONS_FETCH_STARTED = 'WORKSHOP_LOCATIONS_FETCH_STARTED';
export const WORKSHOP_LOCATIONS_FETCH_SUCCESS = 'WORKSHOP_LOCATIONS_FETCH_SUCCESS';
export const WORKSHOP_LOCATIONS_FETCH_ERROR = 'WORKSHOP_LOCATIONS_FETCH_ERROR';

export const WORKSHOPS_FETCH_STARTED = 'WORKSHOPS_FETCH_STARTED';
export const WORKSHOPS_FETCH_SUCCESS = 'WORKSHOPS_FETCH_SUCCESS';
export const WORKSHOPS_FETCH_ERROR = 'WORKSHOPS_FETCH_ERROR';

export const YEAR_CAPACITY_FETCH_STARTED = 'YEAR_CAPACITY_FETCH_STARTED';
export const YEAR_CAPACITY_FETCH_SUCCESS = 'YEAR_CAPACITY_FETCH_SUCCESS';
export const YEAR_CAPACITY_FETCH_ERROR = 'YEAR_CAPACITY_FETCH_ERROR';
export const YEAR_CAPACITY_POLL_CYCLE_FINISHED = 'YEAR_CAPACITY_POLL_CYCLE_FINISHED';
export const YEAR_CAPACITY_POLL_START = 'YEAR_CAPACITY_POLL_START';
export const YEAR_CAPACITY_POLL_STOP = 'YEAR_CAPACITY_POLL_STOP';

export const YEARS_FETCH_STARTED = 'YEARS_FETCH_STARTED';
export const YEARS_FETCH_SUCCESS = 'YEARS_FETCH_SUCCESS';
export const YEARS_FETCH_ERROR = 'YEARS_FETCH_ERROR';
