export const APP_MOUNTED = 'APP_MOUNTED';
export const ACCOMODATION_MOUNTED = 'ACCOMODATION_MOUNTED';
export const CONDITIONS_MOUNTED = 'CONDITIONS_MOUNTED';
export const FEES_MOUNTED = 'FEES_MOUNTED';
export const FOOD_MOUNTED = 'FOOD_MOUNTED';
export const HOME_MOUNTED = 'HOME_MOUNTED';
export const SCHEDULE_MOUNTED = 'SCHEDULE_MOUNTED';
export const TIPS_MOUNTED = 'TIPS_MOUNTED';
export const WORKSHOP_DETAIL_MOUNTED = 'WORKSHOP_DETAIL_MOUNTED';
export const WORKSHOPS_MOUNTED = 'WORKSHOPS_MOUNTED';

export const ACCOMODATION_FETCH_STARTED = 'ACCOMODATION_FETCH_STARTED';
export const ACCOMODATION_FETCH_SUCCESS = 'ACCOMODATION_FETCH_SUCCESS';
export const ACCOMODATION_FETCH_ERROR = 'ACCOMODATION_FETCH_ERROR';

export const CONDITIONS_CURRENT_FETCH_STARTED = 'CONDITIONS_CURRENT_FETCH_STARTED';
export const CONDITIONS_CURRENT_FETCH_SUCCESS = 'CONDITIONS_CURRENT_FETCH_SUCCESS';
export const CONDITIONS_CURRENT_FETCH_ERROR = 'CONDITIONS_CURRENT_FETCH_ERROR';

export const FOOD_TIMES_FETCH_STARTED = 'FOOD_TIMES_FETCH_STARTED';
export const FOOD_TIMES_FETCH_SUCCESS = 'FOOD_TIMES_FETCH_SUCCESS';
export const FOOD_TIMES_FETCH_ERROR = 'FOOD_TIMES_FETCH_ERROR';

export const NEWS_FETCH_STARTED = 'NEWS_FETCH_STARTED';
export const NEWS_FETCH_SUCCESS = 'NEWS_FETCH_SUCCESS';
export const NEWS_FETCH_ERROR = 'NEWS_FETCH_ERROR';

export const TEXT_FETCH_STARTED = 'TEXT_FETCH_STARTED';
export const TEXT_FETCH_SUCCESS = 'TEXT_FETCH_SUCCESS';
export const TEXT_FETCH_ERROR = 'TEXT_FETCH_ERROR';

export const TIPS_FETCH_STARTED = 'TIPS_FETCH_STARTED';
export const TIPS_FETCH_SUCCESS = 'TIPS_FETCH_SUCCESS';
export const TIPS_FETCH_ERROR = 'TIPS_FETCH_ERROR';

export const WORKSHOP_DETAIL_FETCH_STARTED = 'WORKSHOP_DETAIL_FETCH_STARTED';
export const WORKSHOP_DETAIL_FETCH_SUCCESS = 'WORKSHOP_DETAIL_FETCH_SUCCESS';
export const WORKSHOP_DETAIL_FETCH_ERROR = 'WORKSHOP_DETAIL_FETCH_ERROR';

export const WORKSHOPS_FETCH_STARTED = 'WORKSHOPS_FETCH_STARTED';
export const WORKSHOPS_FETCH_SUCCESS = 'WORKSHOPS_FETCH_SUCCESS';
export const WORKSHOPS_FETCH_ERROR = 'WORKSHOPS_FETCH_ERROR';

export const YEARS_FETCH_STARTED = 'YEARS_FETCH_STARTED';
export const YEARS_FETCH_SUCCESS = 'YEARS_FETCH_SUCCESS';
export const YEARS_FETCH_ERROR = 'YEARS_FETCH_ERROR';
