export const APP_MOUNTED = 'APP_MOUNTED';
export const HOME_MOUNTED = 'HOME_MOUNTED';

export const NEWS_FETCH_STARTED = 'NEWS_FETCH_STARTED';
export const NEWS_FETCH_SUCCESS = 'NEWS_FETCH_SUCCESS';
export const NEWS_FETCH_ERROR = 'NEWS_FETCH_ERROR';

export const YEARS_FETCH_STARTED = 'YEARS_FETCH_STARTED';
export const YEARS_FETCH_SUCCESS = 'YEARS_FETCH_SUCCESS';
export const YEARS_FETCH_ERROR = 'YEARS_FETCH_ERROR';
