export const HOME_LEFT = 'HOME_LEFT';
export const PAGE_CONTACT_ENTERED = 'PAGE_CONTACT_ENTERED';
export const PAGE_FEES_ENTERED = 'PAGE_FEES_ENTERED';
export const PAGE_FOOD_ENTERED = 'PAGE_FOOD_ENTERED';
export const PAGE_HOME_ENTERED = 'PAGE_HOME_ENTERED';
export const PAGE_PARTICIPANT_HOME_ENTERED = 'PAGE_PARTICIPANT_HOME_ENTERED';
export const PAGE_SIGNUP_ENTERED = 'PAGE_SIGNUP_ENTERED';
export const PAGE_WORKSHOP_CHANGE_ENTERED = 'PAGE_WORKSHOP_CHANGE_ENTERED';
