export const SCHEDULE_EVENTS_FETCH_STARTED = 'SCHEDULE_EVENTS_FETCH_STARTED';
export const SCHEDULE_EVENTS_FETCH_SUCCESS = 'SCHEDULE_EVENTS_FETCH_SUCCESS';
export const SCHEDULE_EVENTS_FETCH_ERROR = 'SCHEDULE_EVENTS_FETCH_ERROR';
export const SCHEDULE_EVENTS_REQUIRED = 'SCHEDULE_EVENTS_REQUIRED';
