export const GEOCODE_LOCATION_FETCH_ERROR = 'GEOCODE_LOCATION_FETCH_ERROR';
export const GEOCODE_LOCATION_FETCH_STARTED = 'GEOCODE_LOCATION_FETCH_STARTED';
export const GEOCODE_LOCATION_FETCH_SUCCESS = 'GEOCODE_LOCATION_FETCH_SUCCESS';
export const GEOCODE_LOCATIONS_RESET = 'GEOCODE_LOCATIONS_RESET';
export const LOCATIONS_FETCH_ERROR = 'LOCATIONS_FETCH_ERROR';
export const LOCATIONS_FETCH_STARTED = 'LOCATIONS_FETCH_STARTED';
export const LOCATIONS_FETCH_SUCCESS = 'LOCATIONS_FETCH_SUCCESS';
export const LOCATIONS_REQUIRED = 'LOCATIONS_REQUIRED';
