export const MEALS_FETCH_ERROR = 'MEALS_FETCH_ERROR';
export const MEALS_FETCH_STARTED = 'MEALS_FETCH_STARTED';
export const MEALS_FETCH_SUCCESS = 'MEALS_FETCH_SUCCESS';
export const MEALS_REQUIRED = 'MEALS_REQUIRED';
