export const PERFORMER_DETAIL_FETCH_ERROR = 'PERFORMER_DETAIL_FETCH_ERROR';
export const PERFORMER_DETAIL_FETCH_STARTED = 'PERFORMER_DETAIL_FETCH_STARTED';
export const PERFORMER_DETAIL_FETCH_SUCCESS = 'PERFORMER_DETAIL_FETCH_SUCCESS';
export const PERFORMER_DETAIL_REQUIRED = 'PERFORMER_DETAIL_REQUIRED';
export const PERFORMERS_FETCH_ERROR = 'PERFORMERS_FETCH_ERROR';
export const PERFORMERS_FETCH_STARTED = 'PERFORMERS_FETCH_STARTED';
export const PERFORMERS_FETCH_SUCCESS = 'PERFORMERS_FETCH_SUCCESS';
export const PERFORMERS_REQUIRED = 'PERFORMERS_REQUIRED';
